/**:
  ros__parameters:
    path: root
    diagnostics:
      type: diagnostic_aggregator/AnalyzerGroup
      path: diagnostics
      analyzers:
        heartbeat_diagnostics:
          type: diagnostic_aggregator/GenericAnalyzer
          path: heartbeat
          startswith: ["diagnostic_publisher"]
          expected: ["diagnostic_publisher: "]
